= Jakarta EE9 TCK Runner for Payara

This is simple wrapper script to run https://github.com/eclipse-ee4j/jakartaee-tck[Jakarta EE9 TCK binaries].
It provides relevant `ts.jte` overrides as well as a vendor implementation of the configuration interface.

The runner will

1. Extract the TCK into clean directory
1. Apply Payara vendor configuration
1. Run additional environment setup needed for tests
1. Run the actual TCK suite and capture its output

== Prerequisites

* Binary build of the TCK,  (`jakartaeetck.zip`)
* Build of glassfish 6  (`latest-glassfish.zip`)
* Build of payara, e.g. nightly from Jenkins (`payara-prerelease.zip`)
* Linux system with
** Java 8 (referenced by `JAVA_HOME` and referenced in the `PATH`)
*** E.g. the following should hold: `export PATH=$JAVA_HOME/bin:$ANT_HOME/bin/:$PATH`
** Ant (referenced by `ANT_HOME`)
** Python (just for `SimpleHTTPServer`)
** Docker (needed for mailserver container)

== How to run

1. copy the binaries into `bundles` directory (`jakartaeetck.zip`,`latest-glassfish.zip`, `payara-prerelease.zip`)
1. run `bundles/run_server`. That's this simple download server on port 8000
1. run run.sh <suiteName> -- this will perform the test under `./cts_home`
1. produce a slim-down report archived by running `./slim-archive.sh <suite-results.tar.gz>`
jakartaeetck.zip

<suiteName> may be one of the TCK suite names. These can be found in jakartaeetck.zip/src/com/sun/ts/tests

== What to configure

Inspect `run.sh` for comments with `(ENV)` concerning other parameters you can set via environment.

If anything else needs to be modified in `ts.jte`, place the line in `ts.overrides.properties`.

Anything concerning configuration of Payara should be possible to set up via ant scripts in `cts-impl/`
