Bean Validation TCK
=======

The directory contains code to build and run CDI tck.

CDI depends on multiple artifacts:
* CDI TCK Impl - the test suite
* CDI TCK Porting package - Few classes to Support for the test suite to introspect CDI state
* CDI TCK Runner - TestNG / Arquillian driver that runs the suite.
* Whole porting package - All of above plus server provisioning

Porting package contains the runner sources in `glassfish-tck-runner`.
That one is a template project, which is slightly modified for full or web mode.
Runner contains dependencies to TCK Impl and Glassfish porting package (which work ok for Payara), as well as deployment exception tranlation magic.

Building and running
--------------------

TCK is not run directly, but similar to other CTS TCKs it is first packaged into a zip file, that (theoretically) can run on other machine.
To build it run `./build.sh`.
This will create the package and links it into parent bundles repository, so it is available for download.

However, the run script (`./run.sh`, obviously) doesn't download it, rather requires the bundle to be present in bundle subdirectory, which is what build script does, so there's no trouble with that.

Script will download payara bundle, configure the server and run the test suite with managed arquillian container.
*Assure no other server instance is running before executing the script*.
Similar to other TCK scripts it does it with an Ant script.
It first runs signature tests against Payara directory, and then executes the runner.


Running a single test
---------------------
````
$ cd cdi/cditck-porting/cdi-tck-glassfish-porting/glassfish-tck-runner
$ mvn test -Dtest=org.jboss.cdi.tck.interceptors.tests.bindings.broken.InvalidTransitiveInterceptorBindingAnnotationsTest
````

Managed container is started in debug mode by default, so you can attach to server on port 9009.

Fixing the runner
-----------------

This is bit long handed, because one needs to fix things in `cditck-porting/glassfish-tck-runner`, build the bundle again, have `run.sh` unpack it and then verify in `cditck-porting/cdi-tck-glassfish-porting/glassfish-tck-runner`.
